### ISSUE TITLE
按需导入与CDN导入

### ISSUE THREAD

**Issue by npmrun** [Tyh2001/tyh-ui#32]
没有按需导入跟CDN导入吗？全量导入太重了

**Comment by Tyh2001** [comment]
近期更新～可以试一下全新组件库 [fighting- design](https://fighting.tianyuhao.cn/)

**Comment by Tyh2001** [comment]
可以按需导入的，参考：
https://tianyuhao.cn/v3/#/component/install

@npmrun

**Comment by Tyh2001** [comment]
在近期的 4.0.0 版本会推出，你在使用吗？
@npmrun
